//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arayuz.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KitapProjesiEntities : DbContext
    {
        public KitapProjesiEntities()
            : base("name=KitapProjesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Giris> Giris { get; set; }
        public virtual DbSet<KargoFirmasi> KargoFirmasi { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<MailAyarlari> MailAyarlari { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<OdemeYontemi> OdemeYontemi { get; set; }
        public virtual DbSet<Seo> Seo { get; set; }
        public virtual DbSet<SepetID> SepetID { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
        public virtual DbSet<SiparisDurumu> SiparisDurumu { get; set; }
        public virtual DbSet<SiparisGecmisi> SiparisGecmisi { get; set; }
        public virtual DbSet<SiteAyarlari> SiteAyarlari { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeslimatBilgileri> TeslimatBilgileri { get; set; }
        public virtual DbSet<YayinEvleri> YayinEvleri { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
        public virtual DbSet<Kitaplar> Kitaplar { get; set; }
    }
}
