//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arayuz.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seo
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Isım { get; set; }
        public string Harita { get; set; }
        public string AnahtarKelime { get; set; }
    }
}
