//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arayuz.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int Id { get; set; }
        public Nullable<int> KitapID { get; set; }
        public string Yorum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> MusteriID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Kitaplar Kitaplar { get; set; }
    }
}
