//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.SiparisDetays = new HashSet<SiparisDetay>();
            this.Yorumlars = new HashSet<Yorumlar>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string Resim { get; set; }
        public string Aciklama { get; set; }
        public string StokKodu { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public string Yazar { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<int> YayinEviID { get; set; }
        public Nullable<int> TeslimatID { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual TeslimatBilgileri TeslimatBilgileri { get; set; }
        public virtual YayinEvleri YayinEvleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlars { get; set; }
    }
}
