//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KitapProjesiEntities : DbContext
    {
        public KitapProjesiEntities()
            : base("name=KitapProjesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Giris> Giris { get; set; }
        public virtual DbSet<KargoFirmasi> KargoFirmasis { get; set; }
        public virtual DbSet<Kategoriler> Kategorilers { get; set; }
        public virtual DbSet<MailAyarlari> MailAyarlaris { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Seo> Seos { get; set; }
        public virtual DbSet<SepetID> SepetIDs { get; set; }
        public virtual DbSet<SiparisDurumu> SiparisDurumus { get; set; }
        public virtual DbSet<SiparisGecmisi> SiparisGecmisis { get; set; }
        public virtual DbSet<SiteAyarlari> SiteAyarlaris { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeslimatBilgileri> TeslimatBilgileris { get; set; }
        public virtual DbSet<Yorumlar> Yorumlars { get; set; }
        public virtual DbSet<Siparis> Siparis1 { get; set; }
        public virtual DbSet<YayinEvleri> YayinEvleris { get; set; }
        public virtual DbSet<OdemeYontemi> OdemeYontemis { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetays { get; set; }
        public virtual DbSet<Kitaplar> Kitaplars { get; set; }
    }
}
